language: python
python:
  - "2.7"
cache:
#  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/build/docker
    - $TRAVIS_BUILD_DIR/tmp/pex
    - $TRAVIS_BUILD_DIR/tmp/pip
services:
  - docker
install: true
stages:
#  - flake8
  - build
#  - test-cluster-3.4
#  - test-cluster-3.2
#  - test-replset-3.4
#  - test-replset-3.2
#  - test-replset-3.0
#  - test-archive-none
#  - test-archive-zbackup
  - name: deploy-dockerhub
    if: branch =~ ^\d+\.\d+\.\d+$ AND tag =~ ^\d+\.\d+\.\d+$
  - name: deploy-github
    if: branch =~ ^\d+\.\d+\.\d+$ AND tag =~ ^\d+\.\d+\.\d+$
jobs:
  include:
#    - stage: flake8
#      script:
#        - pip install flake8
#        - make flake8
    - stage: build
      script:
        - make docker
        - docker run --rm -it mongodb_consistent_backup:latest --version
        - mkdir -p $TRAVIS_BUILD_DIR/build/docker
        - docker save mongodb_consistent_backup:latest >$TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#    - stage: test-cluster-3.4
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.4
#    - stage: test-replset-3.4
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4
#    - stage: test-cluster-3.2
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.2
#    - stage: test-replset-3.2
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.2
#    - stage: test-replset-3.0
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.0
#    - stage: test-archive-none
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 --archive.method=none
#    - stage: test-archive-zbackup
#      script:
#        - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
#        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 --archive.method=zbackup
    - stage: deploy-dockerhub
      script: true
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - docker load -i $TRAVIS_BUILD_DIR/build/docker/mongodb_consistent_backup.tar
          - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          - docker push $DOCKERHUB_PATH:latest
          - docker push $DOCKERHUB_PATH:$TRAVIS_TAG
        on:
          tags: true
    - stage: deploy-github
      script: true
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - $TRAVIS_BUILD_DIR/build/rpm/RPMS/x86_64/mongodb_consistent_backup-$TRAVIS_TAG-1.el7.centos.x86_64.rpm"
          - $TRAVIS_BUILD_DIR/bin/mongodb-consistent-backup.el7.centos.x86_64
        on:
          tags: true
