language: python
python:
  - "2.7"
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/docker
    - $TRAVIS_BUILD_DIR/tmp/pex
    - $TRAVIS_BUILD_DIR/tmp/pip
services:
  - docker
install: 'pip install virtualenv'
stages:
  - flake8
  - build
  - test-cluster-3.4
  - test-cluster-3.2
  - test-replset-3.4
  - test-replset-3.2
  - test-replset-3.0
  - test-archive-none
  - test-archive-zbackup
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$
jobs:
  include:
    - stage: flake8
      script:
        - pip install flake8
        - make flake8
    - stage: build
      script:
        - make docker
        - docker run --rm -it mongodb_consistent_backup:latest --version
        - mkdir -p $TRAVIS_BUILD_DIR/docker
        - docker save mongodb_consistent_backup:latest >$TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
    - stage: test-cluster-3.4
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.4
    - stage: test-replset-3.4
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4
    - stage: test-cluster-3.2
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-cluster.sh 3.2
    - stage: test-replset-3.2
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.2
    - stage: test-replset-3.0
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.0
    - stage: test-archive-none
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 --archive.method=none
    - stage: test-archive-zbackup
      script:
        - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
        - $TRAVIS_BUILD_DIR/scripts/travis-ci/run-replset.sh 3.4 --archive.method=zbackup
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script:
          - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          - docker load -i $TRAVIS_BUILD_DIR/docker/mongodb_consistent_backup.tar
          - docker push "$DOCKERHUB_PATH:latest"
          - docker push "$DOCKERHUB_PATH:$TRAVIS_TAG"
        on:
          tags: true
